### ISSUE TITLE
Error when stocks number exceeds a certain num in 训练验证集分割效果展示.ipynb

### ISSUE THREAD

**Issue by stargazer110** [dayzorro/GPLearnFinance3D#6]
showing unfitness of size error when enlarging stock number to 150：

ValueError                                Traceback (most recent call last)
Cell In[129], line 1
----> 1 gp_sample.fit_3D(X, Y,feature_names,sample_weight=sample_weight,standard_expression="TRA ((pearson_3d>=0.02) and (spearman_3d >=0.002)) OOB (pearson_3d>0.0002)",need_parallel=True)

File [GPLearnFinance3D-main\GPLearnFinance3D-main\Demo\..\genetic.py:566], in BaseSymbolic.fit_3D(self, X, y, feature_names, baseIC, sample_weight, standard_expression, need_parallel)
    561 for fitness_function_name, fitness_funcion in _fitness_map.items():
    562     cal_function = cal_function.replace(fitness_function_name,
    563                                         "_fitness_map['{}']".format(
    564                                             fitness_function_name) + cal_code)
--> 566 current_result = eval(cal_function)
    567 condition = condition and current_result
    568 if not condition:

File :1

File [GPLearnFinance3D-main\GPLearnFinance3D-main\Demo\..\functions.py:60], in _Function.__call__(self, *args)
     58     return self.function(*args,self.baseConst)
     59 else:
---> 60     return self.function(*args)

ValueError: operands could not be broadcast together with shapes (143,151) (20449,22801)

Enlarging n_components and tournament size seems to fix this.

**Comment by side-walker-s1mple** [comment]
see my issue & your problem will not happen. Basically, this problem is generated by replacement of the constant in the representation, I guess the constant can not actually be random, so if you have 2 constants, your representation will be replace twice.

**Comment by side-walker-s1mple** [comment]
143 ** 2= 20449， 151 **2 = 22801， your constant matrix is replaced twice

**Comment by stargazer110** [comment]
Great, you're right. And the efficiency is greatly improved by this.
